// Generated by https://quicktype.io

export interface TokenInvalidInterface {
  errors: ErrorElement[];
  data:   null;
}

export interface ErrorElement {
  message:    string;
  locations:  Location[];
  path:       string[];
  extensions: Extensions;
}

export interface Extensions {
  code:      string;
  exception: Exception;
}

export interface Exception {
  name:       string;
  message:    string;
  expiredAt:  string;
  stacktrace: string[];
}

export interface Location {
  line:   number;
  column: number;
}
